#!/bin/bash
TACTICIANDIR=$(opam var coq:lib)/user-contrib/Tactician
TACTICIANFLAGS="-q -I $TACTICIANDIR -R $TACTICIANDIR Tactician -rifrom Tactician Ltac1.Record"
/tmp/tactician.coqc.real ${TACTICIANFLAGS} "$@"
