#!/bin/bash
TACTICIANLIB=$(opam var coq-tactician:lib)
TACTICIANDIR=$(opam var coq:lib)/user-contrib/Tactician
TACTICIANFLAGS="-q -I $TACTICIANDIR -R $TACTICIANDIR Tactician -rifrom Tactician Ltac1.Record "
TACTICIANFLAGS+=$TACTICIANEXTRAFLAGS
$TACTICIANLIB/coqc.real ${TACTICIANFLAGS} "$@"
