#!/bin/bash
set -eu

OPAMBIN=$(opam var bin)
TACTICIANLIB=$(opam var coq-tactician:lib)

bwrap --dev-bind / / --bind $OPAMBIN/coqc $TACTICIANLIB/coqc.real \
      --bind $TACTICIANLIB/coqc $OPAMBIN/coqc "$@"
