name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml (4.11)
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.11

      - name: Add Coq OPAM repositories
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
          opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev

      # - name: Install Coq 8.11.2 with test dependencies
      #   run: opam install -y -j 2 -t coq.8.11.2

      - name: Now try to install from the repo
        run: opam install . --deps-only --with-test

      - name: Dune
        run: |
          eval $(opam env)
          dune build
          dune install

      - name: stdlib installation
        run: opam install coq-tactician-stdlib